name: Build and Deploy Website
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Run Deploy Script
        run: ./.github/scripts/backend_decrypt.sh
        shell: bash
