name: Build and Deploy Website
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Configure Git
        run: |
          git config --global user.name "Deploy Script"
          git config --global user.email "<>"
      - name: Deploy
        run: |
          cd build
          echo 'cykreet.com' > CNAME

          git init
          git checkout -b main
          git add -A
          git commit -m 'deploy'

          git push -f git@github.com:cykreet/cykreet.com.git main:gh-pages
          cd -
